const ssb1Desc = `This ground floor is luxuriously appointed 1200sqft 3 bedroom, 2 bathroom oceanfront home with gourmet granite kitchen, dinning area and living room with fireplace.  Unobstructed ocean views from Ranchos Palos Verdes to Santa Catalina Island. Large outdoor patio for relaxing in the sun.`

const ssb2Desc = `This home offers an unbelievable 3800 sq ft of space that includes 5 bedrooms and 4.5 baths along with a 2 car garage and an awesome rooftop deck with a fireplace. Four of the bedrooms in the home offer king size beds and the fifth bedroom has 2 sets of bunk beds for the kids. The kitchen is a cooks dream and the dining area has enough seating for everybody in your party.
Whether it's sitting if front of the High Definition Plasma Televisions watching your favorite movie or sporting event or relaxing in front of an evening fire on the rooftop deck, no matter how you choose to unwind from a fun day at the beach this home is the perfect answer. Call today and book your perfect family getaway.`

const sealBeachDesc = `Villas of Mirada is just walking minutes away from Ritz Carlton Hotel. This Tuscan styled San Gorgonio model the largest, with attached casita is at the end of a cul-de-sec, at the highest location, affording the utmost privacy with unmatched views. It is loaded with top-of-the line finishes and upgrades throughout, including a gourmet kitchen worthy of a professional chef! Two stone fireplaces, including one in the covered, outdoor loggia, off of the great room and master. Custom infinity pool and spa look out to gorgeous mountain views and city lights. This is a private, intimate neighborhood located only minutes from Restaurant Row, theatres and shopping. A homeowners dream!`

const lakeArrowDesc = `PERMITTED and LEGAL Rental. This three-story luxury home is nestled in a gated community upon a lush hillside property. Our home is lakefront with a short 100 yard walk to our own single slip dock. Lake Arrowhead is a private lake. For boat charters and water skiing, BEST option is to make arrangements with Mckenzie Water Ski School and they are fantastic! https://mckenziewaterskischool.com/ They can do boat charters, tours, skiing, wake board..etc! Lake Arrowhead is flourished with trees and breathtaking scenery. This location is perfect for medium to larger-sized families. There is a private wooded path that leads you to a secluded shoreline along Lake Arrowhead. The yard is beautifully maintained complete with two lawn sides, BBQ, and lounging areas. There are multiple balconies allowing you to splendor over the beautifully landscaped grounds. Inside, you have access to a full-size wet bar for spirits. If you enjoy cooking, you can impress friends and family with fancy cuisine cooked up in the executive style kitchen. Afterward, you can play a fun game of Ping-Pong while listening to your favorite music on the central music system. Create a warm ambiance and wind down in the living room beside the fireplace while you watch a movie on the 70” flat screen television. Every aspect of this home offers a plethora of amenities. Be further impressed as this home has an additional sauna and a full-size laundry room. Every restroom has heated floors and every bedroom has its own television and bathroom complete with a rain shower. For additional comfort, each level has its own heat and air control.`

const ranchoDesc = `Villas of Mirada is just walking minutes away from Ritz Carlton Hotel. This Tuscan styled San Gorgonio model the largest, with attached casita is at the end of a cul-de-sec, at the highest location, affording the utmost privacy with unmatched views. It is loaded with top-of-the line finishes and upgrades throughout, including a gourmet kitchen worthy of a professional chef! Two stone fireplaces, including one in the covered, outdoor loggia, off of the great room and master. Custom infinity pool and spa look out to gorgeous mountain views and city lights. This is a private, intimate neighborhood located only minutes from Restaurant Row, theatres and shopping. A homeowners dream!`
const coloRiver1Desc = `Our Colorado river front vacation rental homes are located minutes from Laughlin, Bullhead City and Lake Havasu in near by Mohave Valley, AZ. This vacation rental property contains park like settings with manicured lawn.  Many palm trees accented with night-lights located throughout grounds.  River rentals also feature private docks with parking for boats and personal water craft.   Both Colorado river rental homes feature central air & heat and are fully furnished including all appliances, washer & dryer, TV’s and outdoor charcoal BBQ.  Homes have an incredible view of the Colorado river and mountains and are located only a few feet from the water. `
const coloRiver2Desc = `1328 Dike Rd. is a nice 4000 sqft. home.  It features 4 bedrooms 3 bathrooms, , living room, kitchen and breakfast nook and custom BBQ.  It is equipped with central air and is fully furnished to accommodate any length of stay.  Property features a private dock which can park 2 boats and personal water craft.  Sleeps 12 in beds.`


export const desc = {
    ssb1Desc,
    ssb2Desc,
    sealBeachDesc,
    lakeArrowDesc,
    ranchoDesc,
    coloRiver1Desc,
    coloRiver2Desc
}